#pragma config(Sensor, in1,    clawAngle,      sensorPotentiometer)
#pragma config(Sensor, in3,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in4,    midLine,        sensorLineFollower)
#pragma config(Sensor, in5,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in7,    turnAngle,      sensorGyro)
#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bumber,         sensorTouch)
#pragma config(Sensor, dgtl2,  clawStop,       sensorTouch)
#pragma config(Sensor, dgtl4,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10, leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl7, 1000)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           verticleClawMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl10, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*  			1)Task display displays battery life on the main bettry and updates every 100 miliseconds.  *|
|*				2)BASE_TIME = 0.5m*time
					3)ROUND_DIST = 5.5*2*PI = 34.56																																		*|

|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor   								*|
|*		Digital port 1      touchSensor1        VEX 3-wire module     Front bumber sensor								*|
|*		Digital port 2      touchSensor2        VEX 3-wire module     Claw stop sensor									*|
|*		Analog port 8       lightSensor         VEX 3-wire module     Ambient light sensor							*|
|*		Digital port 4      sonarSensor         VEX 3-wire module     Front distance sensor							*|
|*		Digital port 5      sonarSensor  				VEX 3-wire module     Front distance sensor							*|
|*		Digital port 7-8    rightEncoder 				VEX 3-wire module			Left side encoder									*|
|*		Digital port 10-11  leftEncoder				  VEX 3-wire module			Right side encoder								*|
|*		Analog port 1       poteniometer				VEX 3-wire module			Claw poteniometer									*|
\*----------------------------------------------------------------------------------------------------*/
const int FULL_FORWARD = 127;
const int BASE_DIST = 518;
bool b_f = true;
task display(){
		bLCDBacklight = true;									// Turn on LCD Backlight
	string mainBattery, backupBattery;

	while(true)
	{
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c",);
		displayNextLCDString(mainBattery);

		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
		displayNextLCDString(backupBattery);

		wait1Msec(100);
	}
}
void resetEncoder(){
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
}

void drive(int driveDistance, bool b_f){
	int dir = (b_f)? (1):(-1);
		while (SensorValue[leftEncoder] < driveDistance && SensorValue[rightEncoder] < driveDistance){
		if (SensorValue[leftEncoder] < SensorValue[rightEncoder]){
				motor[leftMotor] = FULL_FORWARD*dir;
				motor[rightMotor] = (FULL_FORWARD-13)*dir;
		}
		if (SensorValue[leftEncoder] > SensorValue[rightEncoder]){
				motor[leftMotor] = (FULL_FORWARD-13)*dir;
				motor[rightMotor] = FULL_FORWARD*dir;
		}
		if (SensorValue[leftEncoder] == SensorValue[rightEncoder]){
				motor[leftMotor] = FULL_FORWARD*dir;
				motor[rightMotor] = FULL_FORWARD*dir;
		}
	}
}
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	StartTask(display);
	wait1Msec(2000);
	for(int i=1;i<6;i++){
		resetEncoder();
		drive(BASE_DIST*i,true);
		resetEncoder();
	  drive(BASE_DIST*i,false);
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
