#pragma config(Sensor, in1,    clawAngle,      sensorGyro)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in4,    midLine,        sensorLineFollower)
#pragma config(Sensor, in5,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in7,    turnAngle,      sensorPotentiometer)
#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bumber,         sensorTouch)
#pragma config(Sensor, dgtl2,  clawStop,       sensorTouch)
#pragma config(Sensor, dgtl4,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl7, 1000)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           verticleClawMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, None, 1000)
#include "../Headers/consts.h"
#include "../Functions/funcs.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//white 1987 black 2851 threshold 2400
/*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor   								*|
|*		Digital port 1      touchSensor1        VEX 3-wire module     Front bumber sensor								*|
|*		Digital port 2      touchSensor2        VEX 3-wire module     Claw stop sensor									*|
|*		Analog port 8       lightSensor         VEX 3-wire module     Ambient light sensor							*|
|*		Digital port 4      sonarSensor         VEX 3-wire module     Front distance sensor							*|
|*		Digital port 5      sonarSensor  				VEX 3-wire module     Front distance sensor							*|
|*		Digital port 7-8    rightEncoder 				VEX 3-wire module			Left side encoder									*|
|*		Digital port 10-11  leftEncoder				  VEX 3-wire module			Right side encoder								*|
|*		Analog port 1       poteniometer				VEX 3-wire module			Claw poteniometer									*|
\*----------------------------------------------------------------------------------------------------*/
task main()
{



}
