<<<<<<< HEAD
#pragma config(Sensor, in1,    turnAngle,      sensorGyro)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in4,    midLine,        sensorLineFollower)
#pragma config(Sensor, in5,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in7,    clawTurn,       sensorPotentiometer)
#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bumber,         sensorTouch)
#pragma config(Sensor, dgtl2,  clawStop,       sensorTouch)
#pragma config(Sensor, dgtl4,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl7, 1000)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           verticleClawMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, None, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Headers/consts.h"
#include "../Functions/funcs.c"

int path[] = {6,1,4,1,3,1,5,2,3,1,3,1,6,2,4,1,4,1,5,2,4,1,4,1,6,
	2,4,1,1,3,1,5,2,3,1,1,4,1,6,2,4,1,1,1,4,1,5,2,4,1,1,1,4,1,6,0};
/*
0=Stop
1=drive forwards
2=drive backwsrds
3=turn left
4=turn Right
5=grab
6=release
7=party
*/
int spot = 0;
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//white 1987 black 2851 threshold 2400
/*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor   								*|
|*		Digital port 1      touchSensor1        VEX 3-wire module     Front bumber sensor								*|
|*		Digital port 2      touchSensor2        VEX 3-wire module     Claw stop sensor									*|
|*		Analog port 8       lightSensor         VEX 3-wire module     Ambient light sensor							*|
|*		Digital port 4      sonarSensor         VEX 3-wire module     Front distance sensor							*|
|*		Digital port 5      sonarSensor  				VEX 3-wire module     Front distance sensor							*|
|*		Digital port 7-8    rightEncoder 				VEX 3-wire module			Left side encoder									*|
|*		Digital port 10-11  leftEncoder				  VEX 3-wire module			Right side encoder								*|
|*		Analog port 1       poteniometer				VEX 3-wire module			Claw poteniometer									*|
\*----------------------------------------------------------------------------------------------------*/
task main()
{
StartTask(control);
StartTask(display);
while (path[spot] != 0) {
	switch (path[spot++]){
	case 1: {
		//drive Forward
		drive(BASE_DIST,true);
	}
	case 2: {
		//drive Backward
		drive(BASE_DIST,false);
	}
	case 3: {
		//turn left
		turn90(false);
	}
	case 4: {
		//turn right
		turn90(true);
	}
	case 5: {
		//grab
		motor[clawMotor] = 127;
		wait1Msec(100);
		motor[clawMotor] = 0;
	}
	case 6: {
		//release
		motor[clawMotor] = -127;
		wait1Msec(100);
		motor[clawMotor] = 0;
	}
	case 7: {
		//party
		motor[verticleClawMotor] = 127;
		wait1Msec(200);
		motor[verticleClawMotor] = 0;
		turn90(true);
		turn90(false);
		turn90(false);
		turn90(true);
	}
	wait1Msec(1000);
	}
	wait1Msec(1000);
}
}
=======
<<<<<<< HEAD
#pragma config(Sensor, in1,    clawAngle,      sensorGyro)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in4,    midLine,        sensorLineFollower)
#pragma config(Sensor, in5,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in7,    turnAngle,      sensorPotentiometer)
#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bumber,         sensorTouch)
#pragma config(Sensor, dgtl2,  clawStop,       sensorTouch)
#pragma config(Sensor, dgtl4,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl7, 1000)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           verticleClawMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, None, 1000)
#include "../Headers/consts.h"
#include "../Functions/funcs.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//white 1987 black 2851 threshold 2400
/*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor   								*|
|*		Digital port 1      touchSensor1        VEX 3-wire module     Front bumber sensor								*|
|*		Digital port 2      touchSensor2        VEX 3-wire module     Claw stop sensor									*|
|*		Analog port 8       lightSensor         VEX 3-wire module     Ambient light sensor							*|
|*		Digital port 4      sonarSensor         VEX 3-wire module     Front distance sensor							*|
|*		Digital port 5      sonarSensor  				VEX 3-wire module     Front distance sensor							*|
|*		Digital port 7-8    rightEncoder 				VEX 3-wire module			Left side encoder									*|
|*		Digital port 10-11  leftEncoder				  VEX 3-wire module			Right side encoder								*|
|*		Analog port 1       poteniometer				VEX 3-wire module			Claw poteniometer									*|
\*----------------------------------------------------------------------------------------------------*/

task main()
{



}
=======
#pragma config(Sensor, in1,    turnAngle,      sensorGyro)
#pragma config(Sensor, in3,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in4,    midLine,        sensorLineFollower)
#pragma config(Sensor, in5,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in7,    clawTurn,       sensorPotentiometer)
#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bumber,         sensorTouch)
#pragma config(Sensor, dgtl2,  clawStop,       sensorTouch)
#pragma config(Sensor, dgtl4,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl7, 1000)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           verticleClawMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, None, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Headers/consts.h"
#include "../Functions/funcs.c"
int path[] = {7,0};
/*
0=Stop
1=drive forwards
2=drive backwards
3=turn left
4=turn Right
5=grab
6=release
7=party
*/
int spot = 0;
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//white 1987 black 2851 threshold 2400
/*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor   								*|
|*		Digital port 1      touchSensor1        VEX 3-wire module     Front bumber sensor								*|
|*		Digital port 2      touchSensor2        VEX 3-wire module     Claw stop sensor									*|
|*		Analog port 8       lightSensor         VEX 3-wire module     Ambient light sensor							*|
|*		Digital port 4      sonarSensor         VEX 3-wire module     Front distance sensor							*|
|*		Digital port 5      sonarSensor  				VEX 3-wire module     Front distance sensor							*|
|*		Digital port 7-8    rightEncoder 				VEX 3-wire module			Left side encoder									*|
|*		Digital port 10-11  leftEncoder				  VEX 3-wire module			Right side encoder								*|
|*		Analog port 1       poteniometer				VEX 3-wire module			Claw poteniometer									*|
\*----------------------------------------------------------------------------------------------------*/
task main()
{
StartTask(control);
StartTask(display);
while (path[spot] != 0) {
	switch (path[spot]){
	case 1: {
		//drive Forward
		drive(BASE_DIST,true);
	}
	case 2: {
		//drive Backward
		drive(BASE_DIST,false);
	}
	case 3: {
		//turn left
		turn90(false);
	}
	case 4: {
		//turn right
		turn90(true);
	}
	case 5: {
		//grab
		motor[clawMotor] = 127;
		wait1Msec(100);
	}
	case 6: {
		//release
		motor[clawMotor] = -127;
		wait1Msec(100);
	}
	case 7: {
		//party
		turn90(true);
		turn90(false);
		turn90(false);
		turn90(true);
	}
	}
}
}
>>>>>>> 2ed1d01b9ef1ffe3631d6941bbeeb39d84db8881
>>>>>>> 822fbceff72b48266cf1c567bdd4d8a4dd281c61
