#pragma config(Sensor, in1,    turnAngle,      sensorGyro)
#pragma config(Sensor, in3,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in4,    midLine,        sensorLineFollower)
#pragma config(Sensor, in5,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in7,    clawAngle,      sensorPotentiometer)
#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  bumber,         sensorTouch)
#pragma config(Sensor, dgtl2,  clawStop,       sensorTouch)
#pragma config(Sensor, dgtl4,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl7, 1000)
#pragma config(Motor,  port6,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           verticleClawMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop, encoder, encoderPort, None, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Headers/consts.h"
#include "../Functions/funcs.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//white 1987 black 2851 threshold 2400
/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*  			Task display displays battery life on the main bettry and updates every 100 miliseconds.		*|
|*				distance of wheel turn = 5.5*2*PI = 34.56		 																								*|
|*				turn90 turns right(True) or left(False) for 90 degrees																			*|
|*				stopMotor and resetEncoder are utility functions to make things easier											*|
|*				this is version 011 or 3 of Robert Robot here he will go forward half a meter and turn			*|
|*				in a path																																										*|
|*				previous versions are version 001 and 010																										*|
|*				you'll find all versions here:																															*|
|*				https://github.com/kartoflu-supa/rob2a																											*|
|*				in the motors & sensors section you will see the name and port of the motors and Sensors		*|
|*				taskmain:																																										*|
|*					1)Starts by going forward 0.5m																														*|
|*					2)then it enters a for loop of turning 90 degrees after array turns then goes forward 		*|
|*						another 0.5m																																						*|
|*					3)once the loop has counted from 0 to 13 the machine and code stops												*|
|*																																																		*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor   								*|
|*		Digital port 1      touchSensor1        VEX 3-wire module     Front bumber sensor								*|
|*		Digital port 2      touchSensor2        VEX 3-wire module     Claw stop sensor									*|
|*		Analog port 8       lightSensor         VEX 3-wire module     Ambient light sensor							*|
|*		Digital port 4      sonarSensor         VEX 3-wire module     Front distance sensor							*|
|*		Digital port 5      sonarSensor  				VEX 3-wire module     Front distance sensor							*|
|*		Digital port 7-8    rightEncoder 				VEX 3-wire module			Left side encoder									*|
|*		Digital port 10-11  leftEncoder				  VEX 3-wire module			Right side encoder								*|
|*		Analog port 1       poteniometer				VEX 3-wire module			Claw poteniometer									*|
\*----------------------------------------------------------------------------------------------------*/
bool l_s = false;
bool r_s = false;
bool m_s = false;
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	StartTask(display);
	StartTask(control);
	motor[clawMotor] = -127;
	wait1Msec(5000);
	motor[clawMotor] = 0;
	while(true){
		int sens = SensorValue[sonar];
		while(SensorValue[midLine] > 1500){
			/*if (sensorvalue[sonar] >0 && SensorValue[sonar] < 21) {
				motor[clawMotor] = 127;
				stopMotor();
				Sleep(1000);
				turn90(true);
				turn90(true);
			}*/

		if (SensorValue[rightLine] > 1500 && SensorValue[leftLine] > 1500) {
			stopMotor();
			motor[clawMotor] = 127;
			wait1Msec(5000);
			motor[clawMotor] = 0;
			gyro_turn(18);
		}
			motor[leftMotor] = 32;
			motor[rightMotor] = 32;
		}
		r_s = SensorValue[rightLine] > 1500;
		l_s = SensorValue[leftLine] > 1500;
		m_s = SensorValue[midLine] > 1500;
		if (l_s == true){
			motor[leftMotor] = -24;
			motor[rightMotor] = 24;
		}
		if (r_s == true){
			motor[leftMotor] = 24;
			motor[rightMotor] = -24;
		}
		}
		if (!(r_s && l_s)) {stopMotor();
			}

	stopMotor();
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
